using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SourceGeneratorToolkit;

/// <summary>
/// Provides a source code builder for source generation.<br/>
/// <c>Append()</c> with interpolated string literal will be optimized to code generation.
/// Please see <see cref="SourceStringHandler"/>.
/// </summary>
/// <example><![CDATA[
/// public static void Emit(SourceProductionContext context, GeneratorAttributeSyntaxContext source)
/// {
///     var builder = new SourceBuilder(source);
///     using (builder.BeginTargetTypeDeclare())
///     {
///         builder.AppendLine($$"""
///             public static string SayHello()
///                 => "Hello, " + typeof({{(INamedTypeSymbol)source.TargetSymbol}});
///             """);
///     }
///     context.AddSource(
///         builder.GetPreferHintName(prefix: "", suffix: ""),
///         builder.Build()
///         );
/// }
/// ]]></example>
internal partial class SourceBuilder : ISourceBuilder
{
    private class State(SourceBuilder owner) : ISourceBuilderState
    {
        private readonly StringBuilder _sourceCode = new();
        public readonly StringBuilder _suspendedCode = new();
        private readonly Stack<string> _indentStack = [];
        private string _currentIndent = "";

        public IFormatProvider FormatProvider => owner.FormatProvider;

        public int IndentLevel => _indentStack.Count;

        private void PushSuspendedCode()
        {
            if (_suspendedCode.Length > 0)
            {
                _sourceCode.Append(_currentIndent);
                _sourceCode.Append(_suspendedCode);
                _suspendedCode.Clear();
            }
        }

        public void Append(ReadOnlySpan<char> value)
        {
            _suspendedCode.Append(value);
        }

        public void Append(ReadOnlyMemory<char> value)
        {
            _suspendedCode.Append(value.Span);
        }

        public void Append(string value)
        {
            _suspendedCode.Append(value);
        }

        public void Append(char c, int repeatCount)
        {
            _suspendedCode.Append(c, repeatCount);
        }

        public void AppendLine()
        {
            PushSuspendedCode();
            _sourceCode.AppendLine();
        }

        public string GetDisplayName(INamedTypeSymbol symbol)
            => owner.GetDisplayName(symbol);

        public StringBuilder GetSuspendedCode()
            => _suspendedCode;

        public void PushIndent(string indent)
        {
            _indentStack.Push(indent);
            _currentIndent = string.Concat(_indentStack);
        }

        public void PopIndent()
        {
            PushSuspendedCode();
            _indentStack.Pop();
            _currentIndent = string.Concat(_indentStack);
        }

        public override string ToString()
            => _sourceCode.ToString() + _suspendedCode.ToString();
    }

    private readonly SemanticModel _semanticModel;
    private readonly List<CodePart> _codeParts = [];
    private readonly int _nameSearchPosition;
    private readonly SyntaxList<UsingDirectiveSyntax> _usings;

    public GeneratorAttributeSyntaxContext Context { get; }

    public IFormatProvider FormatProvider { get; }

    public INamespaceSymbol TargetNamespace => TargetType.ContainingNamespace;

    public INamedTypeSymbol TargetType { get; }

    public CodePart AutoGeneratedComment
        => _autoGeneratedCommend;
    private static readonly CodePart _autoGeneratedCommend = new LiteralCodePart("// <auto-generated/>".AsMemory());

    public CodePart DefaultUsingDirectives
    {
        get
        {
            if(_defaultUsingDirectives is null)
            {
                var usings = string.Join("\n", _usings.Select(static x => x.ToString()));
                _defaultUsingDirectives = new LiteralCodePart(usings.AsMemory());
            }
            return _defaultUsingDirectives;
        }
    }

    private CodePart? _defaultUsingDirectives;

    public CodePart NamespaceDeclaration
    {
        get
        {
            return _namespaceDeclaration ??= new LiteralCodePart(core().AsMemory());

            string core()
                => TargetType.ContainingNamespace is { } ns && !ns.IsGlobalNamespace
                ? $"namespace {TargetType.ContainingNamespace.ToDisplayString()};\n"
                : "";
        }
    }
    private CodePart? _namespaceDeclaration;

    /// <inheritdoc cref="SourceBuilder(GeneratorAttributeSyntaxContext, IFormatProvider, bool" />
    [Obsolete("Specify `usesDefaultHeader` explicitly.")]
    public SourceBuilder(GeneratorAttributeSyntaxContext context)
        : this(context, CultureInfo.InvariantCulture, true)
    {
    }

    /// <inheritdoc cref="SourceBuilder(GeneratorAttributeSyntaxContext, IFormatProvider, bool" />
    public SourceBuilder(GeneratorAttributeSyntaxContext context, bool usesDefaultHeader)
        : this(context, CultureInfo.InvariantCulture, usesDefaultHeader)
    {
    }

    /// <inheritdoc cref="SourceBuilder(GeneratorAttributeSyntaxContext, IFormatProvider, bool" />
    [Obsolete("Specify `usesDefaultHeader` explicitly.")]
    public SourceBuilder(GeneratorAttributeSyntaxContext context, IFormatProvider formatProvider)
        : this(context, formatProvider, true)
    {
    }

    /// <summary>
    /// Creates a new instance of the <see cref="SourceBuilder"/> class.
    /// </summary>
    /// <param name="context">
    /// The <see cref="GeneratorAttributeSyntaxContext"/> instance that provides information about the source generation context.
    /// </param>
    /// <param name="formatProvider">
    /// The <see cref="IFormatProvider"/> instance that provides culture-specific formatting information.
    /// </param>
    /// <param name="usesDefaultHeader">
    /// If <c>true</c>, the generated source code will include a default header comment indicating that it was auto-generated.
    /// For performance reasons, it is recommended to set this argument to <c>false</c> and instead explicitly call <see cref="AppendDefaultHeaders"/> when needed.
    /// </param>
    /// <exception cref="ArgumentException"></exception>
    public SourceBuilder(
        GeneratorAttributeSyntaxContext context,
        IFormatProvider formatProvider,
        bool usesDefaultHeader)
    {
        Context = context;
        FormatProvider = formatProvider;
        TargetType = (context.TargetSymbol as INamedTypeSymbol)
            ?? context.TargetSymbol.ContainingType
            ?? throw new ArgumentException("Target type is null.");
        _semanticModel = context.SemanticModel;

        var cu = context.TargetNode
            .Ancestors()
            .OfType<CompilationUnitSyntax>()
            .First();
        _usings = cu.Usings;
        _nameSearchPosition = cu.ChildNodes()
            .OfType<BaseNamespaceDeclarationSyntax>()
            .FirstOrDefault()
            ?.ChildNodes()
            .FirstOrDefault()
            ?.SpanStart
            ?? _usings.FullSpan.End;
        if (usesDefaultHeader)
        {
            AppendDefaultHeaders();
        }
    }


    public string GetPreferHintName(string? prefix = null, string? suffix = ".g")
    {
        static void writeType(StringBuilder sb, ITypeSymbol type)
        {
            if (type is INamedTypeSymbol namedType)
            {
                sb.Append(namedType.Name);
                if (namedType.TypeArguments.Length > 0)
                {
                    sb.Append($"`{namedType.TypeArguments.Length}");
                }
            }
            else
            {
                sb.Append(type.Name);
            }
        }

        var symbolId = new StringBuilder();
        if (!TargetNamespace.IsGlobalNamespace)
        {
            symbolId.Append($"{TargetNamespace.Name}.");
        }
        foreach (var ancestor in GetAncestors(TargetType.ContainingType))
        {
            writeType(symbolId, ancestor);
            symbolId.Append('+');
        }
        writeType(symbolId, TargetType);
        if (Context.TargetSymbol is IMethodSymbol methodSymbol)
        {
            symbolId.Append($".{methodSymbol.Name}(");
            var separator = "";
            foreach (var param in methodSymbol.Parameters)
            {
                symbolId.Append(separator);
                separator = "-";
                writeType(symbolId, param.Type);
            }
            symbolId.Append(')');
        }
        return $"{prefix}{symbolId}{suffix}.cs";
    }


    public string GetDisplayName(INamedTypeSymbol symbol)
        => symbol.ToMinimalDisplayString(_semanticModel, _nameSearchPosition, SymbolDisplayFormat.MinimallyQualifiedFormat);

    public void Append(CodePart codePart) => _codeParts.Add(codePart);

    public void Append(IEnumerable<CodePart> codeParts) => _codeParts.AddRange(codeParts);

    /// <summary>
    /// Calls <see cref="AppendAutoGeneratedComment"/>, <see cref="AppendDefaultUsingDirectives"/>, and <see cref="AppendNamespaceDeclaration"/>.
    /// </summary>
    public void AppendDefaultHeaders()
    {
        AppendAutoGeneratedComment();
        AppendDefaultUsingDirectives();
        AppendNamespaceDeclaration();
        this.AppendLine();
    }

    /// <summary>
    /// Appends <c>/// &lt;auto-generated&gt;</c> comment.
    /// </summary>
    public void AppendAutoGeneratedComment()
    {
        _codeParts.Add(AutoGeneratedComment);
        _codeParts.Add(CodePart.LineBreak);
    }
    
    /// <summary>
    /// Appends default using directives, which is identical to that of the translation unit that issued the attribute context.
    /// </summary>
    public void AppendDefaultUsingDirectives()
    {
        _codeParts.Add(DefaultUsingDirectives);
        _codeParts.Add(CodePart.LineBreak);
    }

    /// <summary>
    /// Appends namespace declaration for the generation target type.
    /// </summary>
    public void AppendNamespaceDeclaration()
    {
        _codeParts.Add(NamespaceDeclaration);
        _codeParts.Add(CodePart.LineBreak);
    }

    /// <summary>
    /// Begins a new code block by appending an opening brace and increasing the indentation level.
    /// </summary>
    /// <returns>
    /// A disposable object that, when disposed, will close the code block by appending a closing brace and decreasing the indentation level.
    /// </returns>
    public TypeDeclarationScope BeginTargetTypeDeclare()
        => GetPartialTypeDecl(TargetType);

    /// <summary>
    /// Begins a new code block for a partial type declaration of the specified type symbol.
    /// </summary>
    /// <param name="typeName"></param>
    /// <param name="typeKind"></param>
    /// <param name="isRecord"></param>
    /// <param name="typeArguments"></param>
    /// <returns>
    /// A disposable object that, when disposed, will close the code block by appending a closing brace and decreasing the indentation level.
    /// </returns>
    public TypeDeclarationScope BeginFileOnlyTypeDeclare(
        string typeName,
        TypeKind typeKind = TypeKind.Class,
        bool isRecord = false,
        params string[] typeArguments)
    {
        var keyword = GetKeyword(typeKind, isRecord);
        var typeArgumentsDecl = typeArguments.Length > 0
            ? ("<" + string.Join(", ", typeArguments) + ">")
            : "";
        return new TypeDeclarationScope(
            this,
            tpl => $$"""
            {{tpl.attributes}}
            file {{keyword}} {{typeName}}{{typeArgumentsDecl}}{{tpl.baseTypes}}
            {
            """,
            $$"""
            }
            """);
    }

    public string Build()
    {
        var state = new State(this);
        foreach (var codePart in _codeParts)
        {
            codePart.AppendTo(state);
        }
        return state.ToString();
    }


    private TypeDeclarationScope GetPartialTypeDecl(INamedTypeSymbol type)
    {
        var keyword = GetKeyword(type.TypeKind, type.IsRecord);
        var typeArguments = type.TypeArguments.Length > 0
            ? ("<" + string.Join(", ", type.TypeArguments.Select(ta => ta.Name)) + ">")
            : "";
        var containing = type.ContainingType is { }
            ? GetPartialTypeDecl(type.ContainingType)
            : null;
        return new TypeDeclarationScope(
            this,
            tpl => $$"""
            {{tpl.attributes}}
            partial {{keyword}} {{type.Name}}{{typeArguments}}{{tpl.baseTypes}}
            {
            """,
            $$"""
            }
            """,
            containing);
    }

    private static string GetKeyword(TypeKind typeKind, bool isRecord)
        => (typeKind, isRecord) switch
        {
            (TypeKind.Class, false) => "class",
            (TypeKind.Struct, false) => "struct",
            (TypeKind.Interface, false) => "interface",
            (TypeKind.Class, true) => "record class",
            (TypeKind.Struct, true) => "record struct",
            _ => throw new NotSupportedException(),
        };

    private static IEnumerable<INamedTypeSymbol> GetAncestors(INamedTypeSymbol? type)
    {
        if (type is null)
        {
            yield break;
        }
        foreach (var ancestor in GetAncestors(type.ContainingType))
        {
            yield return ancestor;
        }
        yield return type;
    }
}
